### PR TITLE
On new request cancel the previous one (iOS)

### PR DESCRIPTION
**Pull request by Kerumen**
This is a PR for discussion.

I found that I often send multiple requests and I want the result of the last one but not the first one.
Hence, if a new request is sent, I cancel the previous one to submit the new.

As a result in the JS, I will get only the last one instead of the `busy` error.

Let me know if you want this behind a flag or if it doesn't fit. I'm open for discussion.

### CODE REVIEW

**Comment by ryancoughlin** [comment]
Would this have anything to do with getting an error saying the geocoder is busy, but it'll still return location information? I get that on the first time the app builds. Once I refresh it won't happen again. 

I expect the results to be empty, but it does print the town name I am looking for.

**Comment by Kerumen** [comment]
@ryancoughlin If you send 2 requests at a time, yes you get the error saying it's busy. It can be this.
You only get the result of the first request. That's why you still get a result.

@devfd I don't want to hijack all of your repos but if you don't have time anymore I can maintain this one aswell :)

**Comment by Kerumen** [comment]
@devfd Do you have time to maintain your repo?

**Comment by devfd** [comment]
thanks for the PR ;)

**Pull request merged**
